
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  #- job_name: 'prometheus'
  #  static_configs:
  #    - targets: ['localhost:9090']
  - job_name: 'runner'
    honor_labels: true
    static_configs:
      - targets: ['runner:4557']

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# I'm running DockerToolbox, my default VM is at 192.168.99.100
# Prometheus itself is also in default too.
# So put 192.168.99.100:9090 into the browser.
# Runner's port is 4557
